version: '3'

services:
  mysql_db:
    image: mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: Di@z

    volumes:
      - mysql_data:/var/lib/mysql

    restart: always

volumes:
  mysql_data:
