version: '3'

services:
  MySQL_db:
    container_name: MySQL_db
    
    networks:
      - default

    image: mysql

    ports:
      - "3306:3306"
    env_file:
      - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    restart: always

volumes:
  mysql_data:

networks:

 default:

   name: MySQL_db

#  api-backend:

#    external: true